Sup 1223
Lib4RI/lib4ridora pull request #104
Opened 2017-09-21 16:31 UTC by ryanbrinn

2017-09-25 17:44 UTC, qadan commented on lib4ridora.drush.inc
> +        '(RELS_EXT_isMemberOfCollection_uri_ms:"info:fedora/' . $result . '" OR RELS_EXT_isConstituentOf_uri_ms:"info:fedora/' . $result . '")',
Intended to filter pages? Not sure `isConstituentOf` will catch e'm. `isMemberOf` may catch both? Not sure

2017-09-25 17:44 UTC, qadan commented on lib4ridora.drush.inc
> +      if (count($cqp->islandoraSolrResult['response']['objects']) > 0) {
Could skip doing the count on the array and just use `islandoraSolrResult['response']['numFound']`?

2017-09-25 18:01 UTC, adam-vessey requested changes

2017-09-25 18:01 UTC, adam-vessey commented on lib4ridora.drush.inc
> +          'description' => 'The PID of the coolection you wish to purge objects from.',
`s/coolection/collection/`

2017-09-25 18:01 UTC, adam-vessey commented on lib4ridora.drush.inc
> +      'description' => 'Purges objects leaving a small subset for dev purposes.',
Nitpicking, but... percentage could be close to 100%... not necessarily "small"... "smaller" could work... shrug?

2017-09-25 18:01 UTC, adam-vessey commented on lib4ridora.drush.inc
> +    'RELS_EXT_isMemberOfCollection_uri_ms:"info:fedora/' . $collection_pid . '"',
Doesn't appear to be specified on the ticket, but... is this fine only going one level? Or would something like using the `ancestors_ms` bit be preferred to allow it to do transitive things?

2017-09-25 18:01 UTC, adam-vessey commented on lib4ridora.drush.inc
> +    $index++;
Should we only increment when purging? (could get in here if the object disappeared, but we have it listed in `$results`... we didn't purge it, but we want to purge some percentage... shrug? Probably doesn't really matter.

2017-09-25 18:01 UTC, adam-vessey commented on lib4ridora.drush.inc
> +    $result = $pid['solr_doc']['PID'];
Variable names here seem backwards, the `$pid` containing the result, and `$result` containing the PID... just... unexpected?

2017-09-25 18:01 UTC, adam-vessey commented on lib4ridora.drush.inc
> +        '(RELS_EXT_isMemberOfCollection_uri_ms:"info:fedora/' . $result . '" OR RELS_EXT_isConstituentOf_uri_ms:"info:fedora/' . $result . '")',
Could make use of `ancestors_ms`, if it were present. Doesn't appear to be enabled in [their Solr/GSearch config](https://github.com/discoverygarden/lib4ri_solr_config), so ... just wishful thinking, I guess?

2017-09-25 18:01 UTC, adam-vessey commented on lib4ridora.drush.inc
> +    $object = islandora_object_load($result);
Not too concerned given the nature of this script, but... could avoid the `islandora_object_load()` here... try/catch, and use `islandora_get_tuque_connection()` to get a repository instance to purge the object... Something like:
```php
// Probably want the tuque instance outside of the loop, just for minor optimization
// (avoiding the function call to get it).
$tuque = islandora_get_tuque_connection();
try {
  $tuque->repository->purgeObject($the_pid);
  echo "$result\r\n";
}
catch (RepositoryException $e) {
  watchdog_exception('lib4ridora_partial_purge', $e);
  continue;
}
```
IIRC?

2017-09-25 18:01 UTC, adam-vessey commented on lib4ridora.drush.inc
> +    if (in_array($content_model, [
Would it make sense to move this outside of the loop? Throw whatever boolean into a variable, which we just check in each iteration?

2017-09-25 18:01 UTC, adam-vessey commented on lib4ridora.drush.inc
> +    ])
There are other models which can have children... newspapers, newspaper issues, manuscripts, serials... as well as _any_ model, if the ["allow anything to be a compound" bit](https://github.com/Islandora/islandora_solution_pack_compound/blob/cc406b0b94fef509d41513c9de9543ae98c56b98/includes/admin.form.inc#L22-L27) is done... I'm not too familiar with their data... could it be an issue?

Could cover everything by moving to Sparql:
```php
$tuque = islandora_get_tuque_connection();
$the_pid = "islandora:root";
$query = <<<EOQ
ASK {
  ?subject <fedora-model:hasModel> <info:fedora/fedora-system:FedoraObject-3.0> ;
           ?pred <info:fedora/$the_pid> .
}
EOQ;

$child_results = $tuque->repository->ri->sparqlQuery($query);
$has_children = $child_results[0]['k0']['value'] == 'true';
```

Sparql `ASK` queries just look to see if there are any bindings (complete a full `SELECT`)... So asserting there exists an object with any arbitrary relationship to the given object, and allowing it to return "true" after it finds the first one... admittedly, parsing the results of them looks... strange.

2017-09-25 18:01 UTC, adam-vessey commented on lib4ridora.drush.inc
> +          'required;' => FALSE,
Stray semi-colon.

2017-09-25 18:01 UTC, adam-vessey commented on lib4ridora.drush.inc
> +    array_push($qp->solrParams['fq'], 'fedora_datastreams_ms:"' . variable_get('lib4ridora_extra_pdf_datastream_prefix', 'PDF') . '/[0-9A-Za-z]+/"');
Filter appears to be backwards... This would only _select_ those with multiple, wouldn't it? Would have to negate the filter... Also... Not familiar with their use in Solr, but quotes around the regex seems like it could be problematic... Should the prefix just be put into the regex proper?

Also, somewhat of nitpicking, but should generally prefer to append to arrays directly, like:
```php
$qp->solrParams['fq'][] = 'the thing to append';
```

... Altogether, thinking something like:

```php
$qp->solrParams['fq'][] = format_string('-!field:/!prefix[0-9]+/', array(
  '!field' => 'fedora_datastreams_ms',
  '!prefix' => variable_get('lib4ridora_extra_pdf_datastream_prefix', 'PDF'),
));

2017-09-25 18:11 UTC, adam-vessey commented on lib4ridora.drush.inc
> +    array_push($qp->solrParams['fq'], 'fedora_datastreams_ms:"' . variable_get('lib4ridora_extra_pdf_datastream_prefix', 'PDF') . '/[0-9A-Za-z]+/"');
Yeah, looking a bit further into their regex, looks like the query here presently wouldn't really work... Would probably end up causing nothing to be returned?
* `:8080/solr/select?q=fgs_ownerId_ms:"fedora/Admin/"` returns nothing
* `:8080/solr/select?q=fgs_ownerId_ms:/fedoraAdmin/` returns our base objects, as does
* `:8080/solr/select?q=fgs_ownerId_ms:/fedoraAdmi./`

2017-09-26 14:30 UTC, ryanbrinn commented on lib4ridora.drush.inc
> +    'RELS_EXT_isMemberOfCollection_uri_ms:"info:fedora/' . $collection_pid . '"',
I assume only one level but I could be wrong. Should we ask?

2017-09-26 14:36 UTC, adam-vessey commented on lib4ridora.drush.inc
> +    'RELS_EXT_isMemberOfCollection_uri_ms:"info:fedora/' . $collection_pid . '"',
Shrug? Could also just have it documented (and mentioned somewhere during delivery?), and if it turns out they _want_ it to go multiple levels we can iterate... Dunno.

2017-09-26 14:49 UTC, adam-vessey commented on lib4ridora.drush.inc
> +    //'mods_genre_ms:"' . $genre . '"',
Commented out code.

2017-09-26 14:49 UTC, adam-vessey commented on lib4ridora.drush.inc
> +      if ($cqp->islandoraSolrResult['response']['numFound'] > 0) {
Is this check in Solr really necessary now, with the introduction of `$has_children()`? Would just:
```php
if ($has_children($pid)) {
  continue;
}
```
suffice?

2017-09-26 14:49 UTC, adam-vessey commented on lib4ridora.drush.inc
> +    $qp->solrParams['fq'][] =  format_string('-!field:/!prefix[0-9A-Za-z]+/', array(
Coding standards: Looks like there's an extra space after the assignment operator.

2017-09-26 14:49 UTC, adam-vessey commented on lib4ridora.drush.inc
> +      '!field' => 'fedora_datastreams_ms:',
Looks like this would end up with two colons, with the one here and in the format string above (the one here should probably go away).

2017-09-26 15:28 UTC, ryanbrinn commented on lib4ridora.drush.inc
> +      if ($cqp->islandoraSolrResult['response']['numFound'] > 0) {
doh!

2017-09-26 15:30 UTC, ryanbrinn commented on lib4ridora.drush.inc
> +    'RELS_EXT_isMemberOfCollection_uri_ms:"info:fedora/' . $collection_pid . '"',
sounds good
.

2017-09-26 16:19 UTC, adam-vessey commented on lib4ridora.drush.inc
> +      $cqp = new IslandoraSolrQueryProcessor();
Not sure if just overlooked from the [previous comment](https://github.com/discoverygarden/lib4ridora/pull/104#discussion_r141077940), but... shouldn't the body of this `if` block should just be a `continue;`?

2017-09-26 20:20 UTC, adam-vessey commented on lib4ridora.drush.inc
> +      'aliases' => 'lpp',
Should be an array.

2017-09-26 20:29 UTC, adam-vessey commented on lib4ridora.drush.inc
> +function drush_lib4ridora_partial_purge($namespace, $genre, $percentage_purge, $content_model, $collection_pid, $ignore_multiple_pdf = FALSE) {
Options are not actually passed in this way ("arguments" _are_; however, their order is explicit)... Options each have to be separately acquired with `drush_get_option()`... The first lines of this function probably being something like:

```php
$namespace = drush_get_option('namespace');
$genre = drush_get_option('genre');
[...]
$ignore_multiple_pdf = drush_get_option('ignore_multiple_pdf', FALSE);
[...]
```

2017-09-26 20:48 UTC, adam-vessey commented on lib4ridora.drush.inc
> +  $percentage_purge = drush_get_option('precentage_purge');
Typo'd the second "percentage" as "precentage".

2017-09-26 20:51 UTC, adam-vessey approved these changes

2017-09-26 20:52 UTC, merged